name: CI
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14.x", "16.x"]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: test
        run: pnpm test -- --ci --coverage

      - name: upload coverage data
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ci-${{ runner.os }}
          parallel: true

      - name: build
        run: pnpm build

  confirm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
